In [1]:
import tensorflow as tf
X = [1, 2, 4, 5, 6, 7]
Y = [10, 20, 40, 50, 60, 70]

W = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = W * X + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

tf.global_variables_initializer()

for step in range(2001):
    train
    if step % 200 == 0:
        print(step,cost,W,b)

AttributeError: module 'tensorflow' has no attribute 'random_normal'

In [2]:
import tensorflow as tf
X = [1, 2, 4, 5, 6, 7]
Y = [10, 20, 40, 50, 60, 70]

W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

hypothesis = W * X + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

tf.global_variables_initializer()

for step in range(2001):
    train
    if step % 200 == 0:
        print(step,cost,W,b)

AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'GradientDescentOptimizer'

In [3]:
import tensorflow as tf
X = [1, 2, 4, 5, 6, 7]
Y = [10, 20, 40, 50, 60, 70]

W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

hypothesis = W * X + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.optimizers.SGD(learning_rate=0.01)
train = optimizer.minimize(cost)

tf.global_variables_initializer()

for step in range(2001):
    train
    if step % 200 == 0:
        print(step,cost,W,b)

TypeError: minimize() missing 1 required positional argument: 'var_list'

In [4]:
import tensorflow as tf
X = [1, 2, 4, 5, 6, 7]
Y = [10, 20, 40, 50, 60, 70]

W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

hypothesis = W * X + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.optimizers.SGD(learning_rate=0.01)
train = optimizer.minimize(cost,[W,b])

tf.global_variables_initializer()

for step in range(2001):
    train
    if step % 200 == 0:
        print(step,cost,W,b)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable

In [5]:
import tensorflow as tf
X = [1, 2, 4, 5, 6, 7]
Y = [10, 20, 40, 50, 60, 70]

W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

hypothesis = W * X + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.optimizers.SGD(learning_rate=0.01)
train = optimizer.minimize(cost,[W, b])

tf.global_variables_initializer()

for step in range(2001):
    train
    if step % 200 == 0:
        print(step,cost,W,b)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable

In [6]:
import tensorflow as tf
X = [1, 2, 4, 5, 6, 7]
Y = [10, 20, 40, 50, 60, 70]

W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

hypothesis = W * X + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.optimizers.SGD(learning_rate=0.01)
train = optimizer.minimize(cost, var_list=[W, b])

tf.global_variables_initializer()

for step in range(2001):
    train
    if step % 200 == 0:
        print(step,cost,W,b)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable

In [7]:
import tensorflow as tf
X = [1, 2, 4, 5, 6, 7]
Y = [10, 20, 40, 50, 60, 70]

W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

hypothesis = W * X + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.optimizers.SGD(learning_rate=0.01)
train = optimizer.minimize(cost, var_list)

tf.global_variables_initializer()

for step in range(2001):
    train
    if step % 200 == 0:
        print(step,cost,W,b)

NameError: name 'var_list' is not defined

In [9]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

X = [1, 2, 4, 5, 6, 7]
Y = [10, 20, 40, 50, 60, 70]

W = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = W * X + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    sess.run(train)
    if step % 200 == 0:
        print(step,sess.run(cost),sess.run(W),sess.run(b))

Instructions for updating:
non-resource variables are not supported in the long term
0 626.0471 [4.703652] [-0.30587333]
200 0.019935949 [9.939929] [0.31192413]
400 0.0040909965 [9.972788] [0.14130117]
600 0.0008395365 [9.987673] [0.06401039]
800 0.0001723136 [9.994415] [0.02899897]
1000 3.5371948e-05 [9.99747] [0.01313899]
1200 7.264079e-06 [9.998854] [0.00595316]
1400 1.4905727e-06 [9.99948] [0.00269752]
1600 3.067665e-07 [9.9997635] [0.00122452]
1800 6.245924e-08 [9.999893] [0.00055334]
2000 1.32787745e-08 [9.999951] [0.00025345]


In [1]:
tf.__version__

NameError: name 'tf' is not defined

In [2]:
import tensorflow as tf
tf.__version__

'2.1.0'

In [6]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x_data = [[10., 20.],[30.,12.],[25.,35.],[32.,40.]]
y_data = [[5.],[7.],[10.],[12.]]

X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

train = tf.train.GradientDescentOptimizer(learning_rate=0.0001).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(6001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    
    if step % 1500 == 0:
        print("오차 크기: ", cost_val, "\n기존 값에 대한 예측:\n", hy_val,"\n")
        
print("중간고사 20점 / 기말고사 30점일 때, 장학금은? : ", sess.run(hypothesis, feed_dict={X:[[20,30]]}))
print("중간고사 40점 / 기말고사 70점일 때, 장학금은? : ", sess.run(hypothesis, feed_dict={X:[[40,70]]}))

오차 크기:  2362.195 
기존 값에 대한 예측:
 [[34.760017]
 [40.342304]
 [65.86033 ]
 [77.81061 ]] 

오차 크기:  0.115736395 
기존 값에 대한 예측:
 [[ 5.5839405]
 [ 7.165279 ]
 [ 9.95776  ]
 [11.695274 ]] 

오차 크기:  0.109820575 
기존 값에 대한 예측:
 [[ 5.5688195]
 [ 7.161003 ]
 [ 9.958853 ]
 [11.703164 ]] 

오차 크기:  0.10420786 
기존 값에 대한 예측:
 [[ 5.5540953]
 [ 7.15683  ]
 [ 9.95992  ]
 [11.71085  ]] 

오차 크기:  0.09888127 
기존 값에 대한 예측:
 [[ 5.5397477]
 [ 7.1527696]
 [ 9.960957 ]
 [11.718336 ]] 

중간고사 20점 / 기말고사 30점일 때, 장학금은? :  [[8.487218]]
중간고사 40점 / 기말고사 70점일 때, 장학금은? :  [[17.440697]]
